### PR TITLE
Allow delete users

### PR DESCRIPTION
**Pull request by cekk**
I enabled plugins to delete users from the control panel.

I know that every time someone log-in, the user will be re-created, but our customer needs this feature for law reasons (if an user asks to be removed, they need to do it).

An evolution could be adding a blacklist, to avoid some users to be re-created. But right now this is enough for us.

Is it good for you? Or there are some problems that i don't see?

Right now the `User_Adder` and `User_Management` plugins are automatically enabled. We could not activate them automatically, and let the mangers to enable them only if they really need it.

I've also refactored the tests, because using coredev buildouts, some packages have some broken dependencies (maybe because of the new changes for python3).

Now we use test cfgs (like in new plonecli projects).
Again, let me know if it's ok for you, and i'll cleanup all the remaining things.

I only have a problem with Plone 4.3.x because i need to fix some versions and i don't know how to do it  only for 4.3 with this setup..any ideas?

### CODE REVIEW

**Comment by cekk** [comment]
@jensens i rebased this pr with master to have it up to date.
Do you think this could be a nice feature for the plugin or not?

btw i still have problems with plone 4.3 tests: buildout breaks probably for a setuptools wrong version.

**Comment by cekk** [comment]
nevermind this pr..i think that i made some mistake with the rebase (too many changed files in the list).

I can close it and open a fresh new one with my changes..only if you want to accept delete users feature idea obviously.

**Comment by jensens** [comment]
@cekk +1 just go ahead!

**Comment by cekk** [comment]
New pr: #47

**Pull request closed without merging**
