### PR TITLE
Allow user deletion

### PR DESCRIPTION
**Pull request by cekk**
Added methods and interfaces to allow managers to delete users from Users and groups control panel.

### CODE REVIEW

**Comment by jensens** [comment]
flake-8 setup fails on Python 2.7. Shall we drop Python 2  support? It gets harder and harder to configure all the exceptions in the stacks... Though, I do not need it.

**Comment by cekk** [comment]
I see only errors on plone 4.3, but for 5.0 and 5.1 tests and flake-8 should work.
I'm ok to drop plone 4 support and probably also python2 (i still have some 5.1 sites but it's not a problem) because it's painful dealing with these old stacks.

**Comment by jensens** [comment]
ok, lets drop Plone 4 support and keep Python 2 for now.

**Comment by jensens** [comment]
and lets drop Plone 5.0.x - its anyway no longer supported.

**Pull request merged**
